# A template that creates a Plans service
# Version: da39a3ee5e6b4b0d3255bfef95601890afd80709
#
# Copyright 2018 Melon Software Ltd (UK), all rights reserved.  Used under license.
#
AWSTemplateFormatVersion: "2010-09-09"
Description: "Creates a Plans service environment"

Parameters:

    Environment:
        Type: "String"
        Description: "The name of the environment"

    # The second part of the CIDR block for the VPN (10.xx.0.0/24).
    VpnCidr:
        Type: "Number"
        MinValue: 0
        MaxValue: 255
        Default: "2"
        Description: "The second digit in the IP range (10.xx.0.0/16).  VPNs with overlapping address spaces cannot be peered."
    MongoDbPeeringId:
        Type: "String"
        Default: ""
        AllowedPattern: "^(vpc|pcx)-[a-z0-9]+|$"
        Description: "VPC ID to create a new peering connection to, or Peering Connection ID to add routes to an existing connection"
    MongoDbPeeringCidr:
        Type: "String"
        Description: "The CIDR range in the peered VPC to route"
        Default: ""
        AllowedPattern: "^((\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2}))|$"
        ConstraintDescription: "Must be a valid IP CIDR range of the form x.x.x.x/x."

Mappings:
    TemplateVersion:
        Self: { Commit: "da39a3ee5e6b4b0d3255bfef95601890afd80709" }
        Infrastructure: { Commit: "baa6e593c00fa6c2fb81a98464977a8d8940a499" }

Metadata:
    "AWS::CloudFormation::Interface":
        ParameterGroups:
          - Label: { default: "Environment" }
            Parameters:
              - "Environment"
          - Label: { default: "Networking" }
            Parameters:
              - "VpnCidr"
              - "MongoDbPeeringId"
              - "MongoDbPeeringCidr"

        ParameterLabels:
            Environment: { default: "Environment" }
            VpnCidr: { default: "VPN CIDR block" }
            MongoDbPeeringId: { default: "MongoDB peering VPC ID" }
            MongoDbPeeringCidr: { default: "MongoDB peering CIDR" }

Conditions:
    CreateVpc: { "Fn::Not": [ { "Fn::Equals": [ { Ref: "MongoDbPeeringCidr" }, "" ] } ] }

Resources:

    ##########################################################################################################
    ## VPC & NETWORKING
    ##########################################################################################################

    VpcStack:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            Parameters:
                Environment: { Ref: "Environment" }
                SubnetConfiguration: "Public A/B, Private A/B"
                PeeringCidr: { Ref: "MongoDbPeeringCidr" }
                PeeringId: { Ref: "MongoDbPeeringId" }
                Project: "plans"
                Service: "vpc"
                VpnCidr: { Ref: "VpnCidr" }
            Tags:
              - { Key: "Name", Value: { "Fn::Sub": "plans-${Environment}-execute" } }
              - { Key: "Management", Value: "managed" }
              - { Key: "Project", Value: "plans" }
              - { Key: "Environment", Value: { Ref: "Environment" } }
              - { Key: "Service", Value: "vpc" }
            TemplateURL: { "Fn::Sub": [ "https://s3.amazonaws.com/${InfrastructureBucketName}/cloudformation/infrastructure/${TemplateVersion}/vpc.yaml", {
                InfrastructureBucketName: { "Fn::ImportValue": "InfrastructureBucketName" },
                TemplateVersion: { "Fn::FindInMap": [ "TemplateVersion", "Infrastructure", "Commit" ] }
            } ] }
            TimeoutInMinutes: 10
        Condition: "CreateVpc"

    ##########################################################################################################
    ##  API GATEWAY
    ##########################################################################################################

    ApiGatewayLambdaExecutionRole:
        Type: "AWS::IAM::Role"
        Properties:
            AssumeRolePolicyDocument:
                Version: "2012-10-17"
                Statement:
                  - Effect: "Allow"
                    Principal: { Service: [ "lambda.amazonaws.com" ] }
                    Action: "sts:AssumeRole"
            ManagedPolicyArns:
              - "arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole"
              - "arn:aws:iam::aws:policy/AWSXrayWriteOnlyAccess"
              - "arn:aws:iam::aws:policy/service-role/AWSLambdaSQSQueueExecutionRole"
            Policies:
              - PolicyName: "default"
                PolicyDocument:
                    Version: "2012-10-17"
                    Statement:
                      - Action:
                          - "secretsmanager:GetSecretValue"
                        Effect: "Allow"
                        Resource: { "Fn::Sub": "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:plans/${Environment}/*" }
                      - Action:
                          - "lambda:InvokeFunction"
                        Effect: "Allow"
                        Resource: { "Fn::Sub": "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:plans-${Environment}-apigateway-execute" }
                      - Effect: "Allow"
                        Action:
                          - "iot:Publish"
                        Resource:
                          - { "Fn::Sub": "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/users/${Environment}/*" }
                          - { "Fn::Sub": "arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/plans/${Environment}/*" }
            RoleName: { "Fn::Sub": "plans-${Environment}-apigateway-${AWS::Region}" }

    ##########################################################################################################
    ##  LAMBDA
    ##########################################################################################################

    LambdaVpcSecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Security group which allows access for AWS Lambda"
            GroupName: { "Fn::Sub": "plans-${Environment}-apigateway-execute" }
            SecurityGroupIngress:
                # All ports open from internal access
              - IpProtocol: "tcp"
                FromPort: "0"
                ToPort: "65535"
                CidrIp: "0.0.0.0/0"
            Tags:
              - { Key: "Name", Value: { "Fn::Sub": "plans-${Environment}-apigateway-execute" } }
              - { Key: "Management", Value: "managed" }
              - { Key: "Project", Value: "plans" }
              - { Key: "Environment", Value: { Ref: "Environment" } }
              - { Key: "Service", Value: "apigateway" }
            VpcId: { "Fn::GetAtt": [ "VpcStack", "Outputs.VpcId" ] }
        Condition: "CreateVpc"

    ApiGatewayLambda:
        Type: "AWS::Lambda::Function"
        Properties:
            Code:
                S3Bucket: { "Fn::ImportValue": "InfrastructureBucketName" }
                S3Key: { "Fn::Sub": [ "lambdas/plans/${TemplateVersion}/apigateway.zip", {
                    TemplateVersion: { "Fn::FindInMap": [ "TemplateVersion", "Self", "Commit" ] }
                } ] }
            Environment:
                Variables:
                    ENVIRONMENT: { Ref: 'Environment' }
                    AWS_ACCOUNT_ID: { Ref: "AWS::AccountId" }
                    ASYNC_QUEUE_URL: { Ref: "AsyncSqsQueue" }
            Handler: "apigateway.handler"
            Runtime: "python3.6"
            Timeout: "30"
            Role: { "Fn::GetAtt" : [ "ApiGatewayLambdaExecutionRole", "Arn" ] }
            FunctionName: { "Fn::Sub": "plans-${Environment}-apigateway-execute" }
            Tags:
              - { Key: "Name", Value: { "Fn::Sub": "plans-${Environment}-apigateway-execute" } }
              - { Key: "Management", Value: "managed" }
              - { Key: "Project", Value: "plans" }
              - { Key: "Environment", Value: { Ref: "Environment" } }
              - { Key: "Service", Value: "apigateway" }
            TracingConfig:
                Mode: "Active"
            VpcConfig: { "Fn::If": [
                "CreateVpc",
                {
                    SubnetIds: { "Fn::Split": [ ",", { "Fn::GetAtt": [ "VpcStack", "Outputs.PrivateSubnetIds" ] } ] },
                    SecurityGroupIds: [ { Ref: "LambdaVpcSecurityGroup" } ]
                },
                { Ref: "AWS::NoValue" }
            ]}

    ApigatewayStack:
        Type: "AWS::CloudFormation::Stack"
        Properties:
            Parameters:
                Project: "plans"
                Environment: { Ref: "Environment" }
                Service: "apigateway"
                LambdaArn: { "Fn::GetAtt": [ "ApiGatewayLambda", "Arn" ] }
                CustomAuthLambdaArn: { "Fn::ImportValue": { "Fn::Sub": "users-${Environment}-CustomAuthLambdaArn" } }
                CreateCustomDomain: "false"
            Tags:
              - { Key: "Name", Value: { "Fn::Sub": "plans-${Environment}-apigateway" } }
              - { Key: "Management", Value: "managed" }
              - { Key: "Project", Value: "plans" }
              - { Key: "Environment", Value: { Ref: "Environment" } }
              - { Key: "Service", Value: "apigateway" }
            TemplateURL: { "Fn::Sub": [ "https://s3.amazonaws.com/${InfrastructureBucketName}/cloudformation/infrastructure/${TemplateVersion}/apigateway.yaml", {
                InfrastructureBucketName: { "Fn::ImportValue": "InfrastructureBucketName" },
                TemplateVersion: { "Fn::FindInMap": [ "TemplateVersion", "Infrastructure", "Commit" ] }
            } ] }
            TimeoutInMinutes: 30

    ##########################################################################################################
    ##  SQS
    ##########################################################################################################

    AsyncSqsQueue:
        Type: "AWS::SQS::Queue"
        Properties:
            DelaySeconds: 0
            QueueName: { "Fn::Sub": "plans-${Environment}-apigateway-async" }
#            RedrivePolicy:
#                deadLetterTargetArn: { Ref: "AsyncDeadLetterTopic" }
#                maxReceiveCount: 1
            VisibilityTimeout: 300

    AsyncDeadLetterTopic:
        Type: "AWS::SNS::Topic"
        Properties:
            DisplayName: "Plans service asynchronous invocation dead-letter queue"
            TopicName: { "Fn::Sub": "plans-${Environment}-apigateway-asyncdlq" }

    AsyncLambdaInvokePermission:
        Type: 'AWS::Lambda::Permission'
        Properties:
            FunctionName: { 'Fn::GetAtt': [ 'ApiGatewayLambda', 'Arn' ] }
            Action: 'lambda:InvokeFunction'
            Principal: 'sqs.amazonaws.com'
            SourceArn: { "Fn::GetAtt": [ 'AsyncSqsQueue', "Arn" ] }

    AsyncLambdaTriggerMapping:
        Type: "AWS::Lambda::EventSourceMapping"
        Properties:
            BatchSize: 1
            Enabled: true
            EventSourceArn: { "Fn::GetAtt": [ 'AsyncSqsQueue', "Arn" ] }
            FunctionName: { Ref: "ApiGatewayLambda" }
